services:
  proxy:
    image: docker.io/traefik:v3.1.2
    ports:
      - 8080:80
      - 8443:443
      - 8888:8080
    command:
      - "--configfile=/etc/traefik/config/traefik.yaml"
    volumes:
      - ${podmansock}:/var/run/docker.sock
      - ./config/letsencrypt:/letsencrypt:rw
      - ./config/traefik/:/etc/traefik/config:ro
      # - ./config/dynamic/dynamic-conf.yaml:/dynamic-conf.yaml
    networks:
      - externa
  
  ddm:
    image: docker.io/nginx
    networks:
      - externa
    restart: always
    volumes:
      - ${pathDDM}:/usr/share/nginx/html:ro

networks:
  externa:
