services:
  proxy:
    image: docker.io/traefik:v3.1.2
    ports:
      - 80:80
      - 443:443
    command:
      - "--configfile=/etc/traefik/config/traefik.yaml"
    volumes:
      - ${podmansock}:/var/run/docker.sock
      - ./config/letsencrypt:/letsencrypt:rw
      - ./config/traefik/:/etc/traefik/config:ro
    networks:
      - externa
    security_opt:
      - "label=disable"

  
  ddm:
    image: docker.io/nginx:1.27.1
    networks:
      - externa
    restart: always
    volumes:
      - ${pathDDM}:/usr/share/nginx/html:ro
      - ./config/nginx:/etc/nginx/conf.d:ro
    security_opt:
      - "label=disable"  

  aahu:
    image: docker.io/traefik/whoami
    networks:
      - externa
    security_opt:
      - "label=disable"


networks:
  externa:
