http:
  routers:
    ddm0:
      entryPoints:
        - web
      middlewares:
        - httpsRedirect
      service: ddmServ
      rule: Host(`ddm.uem.br`) || Host(`www.ddm.uem.br`)
    ddm1:
      entryPoints:
        - websecure
      middlewares:
        - noWebRedirect
        - cacheRedirect
      service: ddmServ
      rule: Host(`ddm.uem.br`) || Host(`www.ddm.uem.br`)
      tls:
        # options: default
        certResolver: meuCertificado
  middlewares:
    httpsRedirect:
      redirectScheme:
        scheme: https
    noWebRedirect:
      redirectregex:
        regex: ^https?://www.ddm.uem.br/(.*)
        replacement: https://ddm.uem.br/${1}
        permanent: true
    cacheRedirect:
      plugin:
        plugin-simplecache:
          path: /tmp
  services:
    ddmServ:
      loadBalancer:
        servers:
          - url: http://ddm:80