http:
  routers:
    ddm0:
      entryPoints:
        - web
      middlewares:
        - httpsRedirect
      service: ddmServ
      rule: Host(`ddm.localhost`) || Host(`www.ddm.localhost`)
    ddm1:
      entryPoints:
        - websecure
      middlewares:
        - noWebRedirect
        - cacheRedirect
      service: ddmServ
      rule: Host(`ddm.localhost`) || Host(`www.ddm.localhost`)
      tls:
        certResolver: meuCertificado
    aahu0:
      entryPoints:
        - web
      middlewares:
        - httpsRedirect
      service: aahuServ
      rule: Host(`aahu.localhost`) || Host(`www.aahu.localhost`)
    aahu1:
    #### Continuar a montar o aahu2
  middlewares:
    httpsRedirect:
      redirectScheme:
        scheme: https
    noWebRedirect:
      redirectregex:
        regex: ^https?://www.ddm.localhost/(.*)
        replacement: https://ddm.localhost/${1}
        permanent: true
    cacheRedirect:
      plugin:
        plugin-simplecache:
          path: /tmp
  services:
    ddmServ:
      loadBalancer:
        servers:
          - url: http://ddm:80