log:
    level: DEBUG

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"

providers:
  docker:
    watch: true
    exposedByDefault: false
  file:
    directory: "/etc/traefik/config"
    watch: true

certificatesResolvers:
  meuCertificado:
    acme:
      email: dioclecio@hotmail.com
      storage: /letsencrypt/acme.json
      # dnsChallenge: 
      #   provider: cloudflare 
      httpChallenge:
        entryPoint: web
