# log:
#     level: DEBUG
# accesslog=true

api:
  # insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: "/etc/traefik/config"
    watch: true

certificatesResolvers:
  ddmCertificado:
    acme:
      email: dmcamelo@uem.br
      storage: /letsencrypt/ddm.json
      # dnsChallenge: 
      #   provider: cloudflare 
      httpChallenge:
        # watch: true
        entryPoint: web
  aahuCertificado:
    acme:
      email: dmcamelo@uem.br
      storage: /letsencrypt/aahu.json
      dnsChallenge: 
        provider: cloudflare 
      # httpChallenge:
      #   # watch: true
      #   entryPoint: web
  cmsCertificado:
    acme:
      email: dmcamelo@uem.br
      storage: /letsencrypt/cms.json
      httpChallenge:
        entryPoint: web

experimental:
  plugins:
    plugin-simplecache:
      moduleName: "github.com/traefik/plugin-simplecache"
      version: "v0.2.1"
