# log:
#     level: DEBUG

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: "/etc/traefik/config"
    watch: true

certificatesResolvers:
  meuCertificado:
    acme:
      email: dmcamelo@uem.br
      storage: /letsencrypt/acme.json
      # dnsChallenge: 
      #   provider: cloudflare 
      httpChallenge:
        # watch: true
        entryPoint: web

experimental:
  plugins:
    plugin-simplecache:
      moduleName: "github.com/traefik/plugin-simplecache"
      version: "v0.2.1"
